### ISSUE TITLE
Combine "Collaboration Summit" and "Summit Organization" tags

### ISSUE THREAD

**Issue by chowdhurian** [nodejs/summit#102]
Looking at the currently opened issues for both, they're the same.

All the closed "Summit Organization" tags were also tagged with "Collaboration Summit".

It doesn't look like the "Summit Organization" tag has added meaning, I suggest that it be removed.

**Comment by joyeecheung** [comment]
"Summit Organization" is separated from "Summit Topic" though - they are the same in the currently open issues because there are no topic issues for Vancouver yet. https://github.com/nodejs/summit/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Summit+Topic%22+ would look more different from https://github.com/nodejs/summit/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Summit+Organization%22+

**Comment by joyeecheung** [comment]
Also collab summit can be tagged differently from vm summit and diagnostic summit.
