### ISSUE TITLE
Post-mortem: Node.js Collaborator Summit Node+JS Interactive 2018

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#134]
Thanks for all of you that attended (in person or remotely) the Node.js Collaborator Summit Vancouver 2018. This is a little post-mortem issue to know what worked well, and what did not work at all.

Let us know what you think about the Vancouver 2018 event so that we could do even better in next year!

**Comment by cjihrig** [comment]
Berlin 2019? 😄

**Comment by apapirovski** [comment]
This isn't so much feedback for next time because we don't have the same venue options in Berlin but if we do Node+JS Interactive again, I would really like us to consider another venue so that we don't need to pass the mic around like we did this time. It makes it really hard to have a proper discussion on some of the more engaging / controversial topics. I thought this worked quite well in Berlin where we had a medium sized room and just passed around the "talking cube".

**Comment by n370** [comment]
As a freshman this year I feel like I just have to thank you for making this open for newcomers and outsiders to experience it. It was great to see all of you there materialized.

**Comment by mhdawson** [comment]
I think overall it was a great summit, kudo's to the organizers.

My one comment would be that I'd prefer we omit the presentations at the start of the summit and try to focus on the interactive sections.  If we do want one-way communication then adding to the lightning talks at the end would be the best way in my opinion.

**Comment by chowdhurian** [comment]
https://github.com/nodejs/summit/issues/134#issuecomment-429672419

> BTW, I saw at a TC39 meeting there was a whiteboard, people would write down a particular topic they want to talk about and their names, then those who are interested in one topic would gather in small groups to chat

Cool idea @joyeecheung. Sounds to me like an unconference format? It could be demo'd in Berlin 2019. It would likely be a split between scheduled sessions like we had and these. 

Possibly, this could be better suited to the Summits attached to Interactive because of the larger audience.

**Comment by mcollina** [comment]
I think we should follow this process:

1. open up a call for session. Each session must have a facilitator that commits to come to the summit.
2. open up a registration link for the summit.
3. one month or less prior to the summit, send a survey with all the sessions that have been selected.
4. assemble the final agenda prior to the summit
5. refresh the agenda on the morning of the summit, and adjust accoordingly.

Wdyt?

**Comment by mhdawson** [comment]
I'm good with 1 through 4, but 5 is a bit of a concern.

Changes to the agenda at the last minute caused confusion last time (people not finding the right room/time I think) and make it potentially harder for remote people who will have planned based on the original agenda.

I understand that some agenda changes may be required but I think they should be a last resort after maybe 1 week before the summit.

**Comment by chowdhurian** [comment]
The best case scenario is def to not make last minute changes. In summits
so far, the last minute changes have been out of necessity because of
logistics changes mainly around venue specifics.

If we can nail down the reasons for the changes and find reasonable ways to
prepare, we could maybe reduce the need for it, but I think a certain
amount is to be expected.

An agenda item for the first sync meeting could be to see if that is
possible 👍🏽

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍
