### ISSUE TITLE
Summit Topic: fetch in Node.js

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#165]
**Topic of the session**

Fetch in Node.js

**Describe the session**

We should discuss how to bring `fetch()` to Node.js. 

**Session facilitator(s) and Github handle(s)** 

@MylesBorins @mcollina 

**Additional context (optional)**

**Comment by benjamingr** [comment]
Would love to attend this. Should this be bigger and scoped to web compatibility or specific to fetch?

 - EventTarget in Node?
 - WhatWG Stream in Node?

**Comment by mcollina** [comment]
I think we should touch those briefly. I’m more concern about the semantic model vs what API we need.

I would like to cover:

1. why we cannot implement the spec as it is
2. where we should diverge from the spec in behavior
3. maybe lessons learned from node-fetch
4. what a new, high-level API for http should like in Node (requirements)
5. ecosystem consequences in matching 1:1 the WhatWG stream API

Regarding WhatWG Streams, they need somebody to lead that initiative. For several reasons, my time is limited, and it’s a significant amount of work.

**Comment by benjamingr** [comment]
> Regarding WhatWG Streams, they need somebody to lead that initiative. For several reasons, my time is limited, and it’s a significant amount of work.

I agree and I think in general most of these have been blocked on the large technical and emotional amount of work doing something like this would take.

I think there would be a lot of benefit in having people who have worked on the fetch spec and people who have worked on the DOM participate in this meeting because I'd rather Node not have to "work around" browser quirks if we can reach a unified model and talk things over.

**Comment by mcollina** [comment]
I spoke with @MylesBorins in NYC, and he said he would try to arrange some folks to come to the summit to discuss this.

I've scheduled this session on the 31st afternoon. @MylesBorins would that work?

**Comment by MylesBorins** [comment]
Can we please have this schedule on the 30th? There are folks in Berlin that would only be able to make it that day that would be great to have in the conversation

**Comment by littledan** [comment]
Cc @annevk

**Comment by benjamingr** [comment]
> (As I mentioned to @littledan I won't be able to make it the 30th as that's a holiday here and the 31st is CSSConf.)

@annevk are you attending CSSConf? If you're in Berlin at the same summit dates we might be able to make time the day before / the day after rather than in the summit itself and meet to discuss this. I think your input is valuable enough to consider this.

**Comment by annevk** [comment]
I'm based in Berlin and plan to attend CSS and JSConf. I'm happy to provide some insights, but ultimately this is something the Node.js community needs to decide and work on, so don't go out of your way for me.

**Comment by benjamingr** [comment]
@annevk thanks, I've had a lot of negative experiences in the past with Node.js not collaborating with standards bodies. Luckily with people like Myles, Matteo and Daniel these have been getting less and less frequent.

The point of `fetch` in Node.js is amongst other things to enable better and easier universal JavaScript. I think we start (mentally) with "let's ship the same fetch" and compromise on things as we go (EventTarget vs. EventEmitter, streams and so on). I think it's important that the people who built fetch participate in those discussions because the stakes of getting this wrong are high :]

**Comment by mcollina** [comment]
> Can we please have this schedule on the 30th? There are folks in Berlin that would only be able to make it that day that would be great to have in the conversation

I've moved it to the 30th.

**Comment by MylesBorins** [comment]
@annevk thanks for chiming in. I'll be around JSConf and perhaps we can find some time to chat.

**Comment by trivikr** [comment]
Do share the zoom link (if available) here when the session starts at **CEST Thu 30-May-2019 15:00 (03:00 PM)**

**Comment by trivikr** [comment]
Time: **CEST Thu 30-May-2019 15:00 (03:00 PM)**
Zoom link: https://zoom.us/j/381668642

**Comment by benjamingr** [comment]
https://docs.google.com/document/d/1tn_-0S_FG_sla81wFohi8Sc8YI5PJiTopEzSA7UaLKM/edit?usp=sharing

**Comment by WaleedAshraf** [comment]
closing as the summit is over. 👍

**Comment by keywordnew** [comment]
Closing as this event is complete :)
