### ISSUE TITLE
Amsterdam: Key Signing Party!

### ISSUE THREAD

**Issue by TheAlphaNerd** [nodejs/summit#27]
A bunch of us have gpg keys. It would be a good idea to use this as an opportunity to sign each others keys in person.

The network of trust is very important

**Comment by indutny** [comment]
Teach me!

**Comment by bengl** [comment]
As a very basic/informal version of this, we can simply bring ID + email address associated with key + **full** GPG fingerprints (e.g. `37D2 6669 8039 4F22 43B7  FF45 145D 4E0D 7970 799A`).

**Comment by indutny** [comment]
Did this party take place? Or is it going to happen tomorrow?

**Comment by TheAlphaNerd** [comment]
tomorrow!

**Comment by indutny** [comment]
what time? ;)

**Comment by bengl** [comment]
@indutny We did do this, not sure what time, but it was whenever the lengthy collaborator summit discussions finished. I'm sorry you missed it!

I'm preparing a quick recap/postmortem doc on what we can improve if we want to do it again in Austin. I'll post it here soon.

**Comment by bengl** [comment]
Here's my "review"/"post-mortem"/"recap" of the keysigning party.

-----

At the Node.js Interactive Collaborator Summit, I facilitated a keysigning party. Like most keysigning parties, there were some attendees with limited experience with GPG or public key cryptography. In addition, an unfortunately low level of planning went into the event.

Luckily, I was able to address some (all?) of the attendees the day before, so I instructed them to be able to provide their GPG fingerprint along with email address and some form of ID. They weren't instructed to bring pieces of paper with fingerprint and email, like a normal keysigning party would involve. This is because of the rather sudden and impromptu planning of the event. Many attendees wouldn't have access to a printer, and wouldn't want to have to laboriously write out many copies of their fingerprint and email on pieces of paper.

Instead, I had everyone put the output of `gpg --fingerprint` in large text on the screens of their laptops, and had them take photos of each other's screens with their smartphones, once ID was verified. This way they have a record of keys they've verified on their smartphones, which they can check later for signing. An email was later sent to the attendees, ensuring that less-experienced would have adequate instructions on how to sign and upload the keys.

Some issues arose though:

* **The scheduling wasn't great.** We weren't very clear on the timing, and had only said something like "At lunch after the collaborators summit discussions have finished". Since the collaborators summit discussions lasted until well after lunch, some folks were waiting for quite some time. Better planning will mostly solve this.
* **While all attendees had laptops, not all attendees had smartphones or cameras.** This was remedied by simply writing down they keys and emails from the screens, but it was certainly time consuming. For next time, a paper handout solution might be more ideal.
* **Showing ID to everyone isn't always reasonable.** As an alternative for next time, maybe participants can sign a block of text after the party and submit it to a known location, like a GitHub issue. I think this works, so long as the block of text is decided upon or distributed at the party only. After all, we're only really trying to verify that the people we meet in person are the people who hold the private keys of the public keys they're presenting. I'd like to see if there are other non-ID approaches taken. (/cc @chromakode for ideas here.)

I would call the event a success. We had around 10 people participate, including several CTC members and several release-team folks (whose keys are used to sign Node.js releases, so it was great to have them there). I think we should probably do it again at Node.js Interactive in Austin with better planning and see how that goes.
