### ISSUE TITLE
Diversity/Inclusivity session at CollabSummit Spring 2018

### ISSUE THREAD

**Issue by Tiriel** [nodejs/summit#75]
Just to prepare at least a little the working session, this is a brief run of the subjects I'd like to go through. Don't hesitate to propose other items of comment these ones, or just to note if you'd like to attend!

* Return on our Inclusivity/Diversity definitions
* Historic of such initiatives in the Node.js Foundation/community (need help with that one)
* How can we make diverse people stay
* General strategies for developing diversity/inclusivity in the Foundation/GH org/community
* Concrete day-to-day inclusive communication

Deeply waiting for your thoughts and participation!

**Comment by Trott** [comment]
> Historic of such initiatives in the Node.js Foundation/community (need help with that one)

I can probably help with that.

One thing I'd love to see focused on here is **retention**. While it's a small challenge to get diverse folks to start contributing to the project, the big challenge is making it something they'll want to stay around for. People (very much including me) tend to want to think about getting people *started* first because it comes first chronologically and because it's an easier problem to solve, but I think we should start with retention. I would go so far as to argue that getting people started is mostly a solved problem (see: Code + Learn, Node Todo, etc.) and that retention is the far more important issue.

**Comment by Tiriel** [comment]
@Trott This is a very, very good point. I wouldn't go as far as you do about getting people started, but I definitely think that the problem is mainly on making a place safe enough to make people actually stay. I'm adding this point to the agenda.

On the historic part, if you can come by and help us having a clear idea of past iterations and why the might have dropped/fail, that would be awesome!

**Comment by Trott** [comment]
> On the historic part, if you can come by and help us having a clear idea of past iterations and why the might have dropped/fail, that would be awesome!

I'll try to make some time to come up with some prepared remarks because (uncharacteristic for me) this is not something that should be explained extemporaneously. That's because how to properly characterize events is a contentious matter. But I think it's also crucial to understanding the challenges before the project. I'll do my best to minimize my own personal biases, and I'll try to get feedback from folks who were involved on all sides of the more contentious matters. Also uncharacteristic for me, I'll do my best to be brief.

**Comment by Trott** [comment]
https://chime.aws/7259704916

**Comment by tlobinger** [comment]
Meeting Link: https://chime.aws/3941259029
Meeting ID: 3941 25 9029
U.S. Toll: +1 206-462-5569
Meeting PIN: 3941 25 9029
U.S. Toll-free: +1 855-552-4463
International: https://chime.aws/dialinnumbers/

**Comment by tlobinger** [comment]
updated the meeting id and started the recording

**Comment by codeekage** [comment]
@tlobinger Please want the name on the attendance meeting. I can't have access to it.

**Comment by tlobinger** [comment]
@codeekage the link is not working for you?

**Comment by tlobinger** [comment]
you can join without creating an account ... I see the room being called in and the recording running ...

**Comment by codeekage** [comment]
@Trott Please, add me to the remote attendees. I can't turn on my mic... because I'm not registered I guess.

**Comment by tlobinger** [comment]
@codeekage can you call in again please? I did not pay attention to you trying.

**Comment by tlobinger** [comment]
https://github.com/nodejsafrica/admin link from @codeekage regarding NodeJSAfrica and the idea of regional templates to instantiate local chapters

**Comment by tlobinger** [comment]
https://s3-eu-west-1.amazonaws.com/ponyhof/2018+05+31+Node.js+Summit+-+diversity+and+inclusion.mp4 here is the recording of the meeting. Feel free to re-upload where you think it belongs to be shared.

**Comment by Trott** [comment]
I imagine we should close these issues once the session is ended. If I'm wrong, re-open or leave a comment! Thanks!

**Comment by codeekage** [comment]
Was they any mintues?

**Comment by Trott** [comment]
> were they any minutes?

Yes. @bnb: Can you share the minutes?

**Comment by codeekage** [comment]
okay... thank you 🙏

**Comment by bnb** [comment]
Minutes for Inclusivity: https://docs.google.com/document/d/1FV8X0xghtFDqwTho6GtsUHeH3uTzY8bmWVP8WGEFkyI/edit?usp=sharing
