### ISSUE TITLE
Post-mortem: Node.js Collaborator Summit Berlin 2018

### ISSUE THREAD

**Issue by mcollina** [nodejs/summit#96]
Thanks for all of you that attended (in person or remotely) the Node.js Collaborator Summit. This is a little post-mortem issue to know what worked well, and what did not work at all.

Let us know what you think about the Berlin 2018 event so that we could do even better in Vancouver this fall #59.

**Comment by benjamingr** [comment]
I think the event was very nice and a lot of work got done. Thank you everyone who had a part in organising it or running sessions. Was my first summit and I was impressed by how nice and welcoming people were.

Also thank you AWS and Mozilla for hosting us.

I think in general the first day's smaller sessions were more effective than the full-room second day sessions and that splitting into groups on the second day was a smart decision.

I think we need to figure out a better way to do remote participation - people actually did tune in and the microphone didn't work.

Other than that I think a lot of important work got done and these events are effective.

**Comment by Trott** [comment]
Things that worked well IMO:

* One or two short presentations by awesome folks to warm things up on the first day.
* Lots of small, focused break-out sessions on the first day.
* Having an agenda set, but being chill about it if people wanted to change things up and add new topics or whatever.
* OMG travel fund.

Things that worked less well:

* Plenary discussions.
  * Plenary *presentations* worked fine (which is why I put it in the previous list of things that worked). 
  * Plenary *discussions* were less valuable (in my view).
    * They tended to be dominated by a few people (I'm one of the guilty parties there).
    * They tended to not advance beyond the conversations on the same topics that already happened online or elsewhere.
    * And (this may be more about me but maybe not?) I personally found them frustrating, especially given how productive the small group conversations had been the previous day.

Kind of interested in what worked and didn't work in terms of organizing. Like, are there things you (@mcollina et al.) did or didn't do that you thought worked or didn't? That sort of thing would be helpful to document for people who organize next year or whenever new people step in to organize.

**Comment by mcollina** [comment]
> Kind of interested in what worked and didn't work in terms of organizing. Like, are there things you (@mcollina et al.) did or didn't do that you thought worked or didn't? That sort of thing would be helpful to document for people who organize next year or whenever new people step in to organize.

There has been an amazing response to the Request for Proposals, which have been fantastic. However this filled up our rooms and agenda, leaving little space for _more_ discussions and last minute things. Space for those discussion was missing.
I accepted and assembled an agenda including _all_ sessions that have been proposed and that received interest. I expect to have even more proposal for the next event, and we might not have enough room for every session. In the future, we would need to select which session we include, and this must be a team decision.

**Comment by Trott** [comment]
> this must be a team decision.

Maybe there's an agenda-making tool that can be used by attendees to determine an agenda ahead of time, perhaps by some sort of voting or something. Maybe we can have some process like http://thatcamp.org/help/organize/scheduling/? Then the agenda is determined ahead of time, but also determined by attendees, and the organizers don't have to make the hard decisions.

**Comment by bnb** [comment]
One of the things that was frustrating that I think could be solved by team scheduling is overlap. Every time block had CommComm sessions, which was absolutely fantastic. That said, the final time block had three concurrent CommComm sessions, so we weren't able to get people who cared and had context into all of them simultaneously.

Having two days would have definitely helped resolved this at the CommComm's current scale, but as we continue to scale up and get more people involved the issue will continue. I don't think it'll ever be entirely avoidable (that's kinda how these things go – you want to be everywhere but have to pick your scope and co-ordinate with others), but instrumentation like what @trott suggested would likely help.

**Comment by joyeecheung** [comment]
We also discussed about getting the V8 team to give the collaborators a talk about the V8 API, explaining the concepts that are not obvious from reading v8.h, since a lot of our collaborators may still not be comfortable with changing or reviewing PRs that touches the C++ part of the code base.

Another idea is to get people who are knowledgeable in subsystems where only a few reviewers are available to do a few talks on those subsystems and get more people comfortable with the design and quirks of those subsystems.

**Comment by joyeecheung** [comment]
Also we discussed about just getting people do a hackthon to fix the flaky tests if it's still in a bad situation in October: we have done this in the JSConf EU and we managed to make the CI less red (according to my random checks on https://nodejs-ci-health.mmarchini.me/#/job-summary before the week in Berlin we are 70%~90% red, after it's down to ~50%). Unlike certain discussions, getting people physically in the same space hacking on spooky bugs together is actually more effective than doing this asynchronously on the issue tracker. We can also do a clean-up of the issue tracker - not just the core issue tracker but also other issue trackers in the org - together, the upside is if someone involved in the discussion is around we can just go ask them instead of pinging them, since GitHub pings get lost all the time given the volume of the notifications.

**Comment by joyeecheung** [comment]
Another idea: I have talked with several people (collaborators and non-collabroators) about us not having a roadmap, and it's hard to see where we are going and establish a vision for the project without a roadmap. One alternative is to let the subsystem teams do a report on each subsystem: what we have done since the last summit, what we plan to do before the next summit, what needs more attention from other collaborators and users, etc. For a lot of subsystems, the answers can probably be concluded as one word - stability. But some other subsystems may have more to say since they are in constant need of improvement e.g. tools, build.

**Comment by mcollina** [comment]
@WaleedAshraf were them on day 1 or day 2?

**Comment by WaleedAshraf** [comment]
1st day @mcollina

**Comment by joyeecheung** [comment]
In my experience, remote participation in discussions is just hard. Unless someone deliberately ask about your opinion, you hardly get to talk and because of the timezone you may not be stay awake enough to keep up at all. Even if someone remember to ask about your opinion, they may already move on from the topic that you want to weigh in. Doing internal talks and sessions where people actually work on something is easier for remote participants to follow.

**Comment by benjamingr** [comment]
>  in our cases since unlike TC39, we do not have any clear agenda and slides ready before the actual summit. 

I think that generally talks that were not explicitly discussions with clear agenda and slides went better than ones without. That's a good takeaway too.

**Comment by mhdawson** [comment]
I agree with @Trott comments that the smaller working sessions worked better than those where we tried to have the discussion with the full group.  

I think a format with a small number of common sessions that are informational or setup the later breakout sessions, followed by smaller breakout sessions work better.  (and understood that his time we were constrained by what was available the 2nd day).

I agree with @joyeecheung that without a roadmap people are looking for as much information as they can get on future directions.  We have the strategic initiatives but adding updates from the subsystem teams and working groups provide additional info.  If we think that is useful for the collab summit I think having a more frequent update for the TSC would be good as well (Maybe every 2 months?).  The first step would be a list of the subsystems along with a volunteer that would be willing to do the updates.

**Comment by ryzokuken** [comment]
+1 on the subsystem updates. The subsystems should do a better job of communicating to the outside world (the TSC first, rest of the collaborators next, general public later) what they've been working on in the recent past and what their plan is for the following period (2 months sounds good, but we could come down to 1 month).
