### ISSUE TITLE
Survey for JS Interactive / Collaboration Summit in Vancouver, Oct. 2018

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/summit#99]
Hi all,

https://goo.gl/forms/RprRhVd9oRfdlxSP2

Please participate in this google form so we can estimate:

- The number of Node.js organization members coming to Vancouver this year and the attendance of the collaboration summit (to know about the space needed)
- The cost of travel funds (and see if we need to allocate more)
- The number of JS Interactive tickets that the foundation may be able to sponsor

Do note that this form is only used for estimation. Filing out this form does not guarantee funding and/or reimbursement. Since the fund is limited and we would want more members to come, please skip the last section about potential funding requests if you don't absolutely need it.

The form will be closed on July 6th, 2018. Member of @nodejs/tsc  and @nodejs/community-committee will review the responses and discuss with the events team of the foundation to determine the number of tickets that can be sponsored.

Refs: https://github.com/nodejs/summit/issues/99

@nodejs/collaborators @nodejs/members

**Comment by benjamingr** [comment]
Hey, there are a few teams missing from the survey as far as I know. Filled :)

I want to make it to the summit as the Berlin one was very effective but I'm still not sure about whether or not I'll be able to attend.

**Comment by joyeecheung** [comment]
@benjamingr There are about ~100 teams so I only picked a few that are most active, I may forgot the others :/ Not sure how to make the Google form accept additional options..may be I can just add a new field?

**Comment by benjamingr** [comment]
@joyeecheung well, if I attend it'll be to make forward progress on the "better async story" stuff we've been working on - we've established https://github.com/nodejs/promises-debugging which is pretty active and are doing a follow-up meeting on the summit on July 12th - https://github.com/nodejs/promise-use-cases/issues/29 

I am a collaborator and a member of some listed teams (like Modules) but that's not really what I'm looking too forward to discuss. Not sure if it's relevant or interesting feedback - but since there was no way to supply it in the form I'm writing it here.

**Comment by joyeecheung** [comment]
The survey has ended, thanks for participating!
